name: Build

on:
    pull_request:
        types:
            - synchronize

jobs:
    build:
        name: Build

        runs-on: ubuntu-22.04

        steps:
            -   uses: actions/checkout@v4

            -   name: Gather Docker metadata
                id: docker-meta
                uses: docker/metadata-action@v4
                with:
                    images: |
                        baldissaramatheus/tasks.md
                    tags: |
                        # Process semver like tags
                        # For a tag x.y.z or vX.Y.Z, output an x.y.z,  x.y and x image tag
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}
                        type=semver,pattern={{major}}

            -   name: Login to Docker Hub
                uses: docker/login-action@v2
                if: github.event_name != 'pull_request'
                with:
                    username: "${{ secrets.DOCKER_USERNAME }}"
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2

            -   name: Build image
                uses: docker/build-push-action@v4
                with:
                    context: .
                    file: ./Dockerfile
                    platforms: linux/amd64,linux/arm/v7,linux/arm64
                    push: false
