name: Build

on:
    pull_request:
        types:
            - opened

jobs:
    build:
        name: Build

        runs-on: ubuntu-22.04

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2

            -   name: Build and push
                uses: docker/build-push-action@v4
                with:
                    context: .
                    file: ./Dockerfile
                    platforms: linux/amd64,linux/arm/v7,linux/arm64
                    push: false
